version: '3.2'

services:

  vote:
    image: xperjon/voting_vote:1.0
    ports:
      - "80"
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        windows: 120s

  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 20s
        failure_action: rollback
      restart_policy:
        condition: on-failure
  
  worker:
    image: xperjon/voting_worker:1.0
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        windows: 120s
      placement:
        constraints:
          - 'node.role == manager'

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      -  backend
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
    
  result:
    image: xperjon/voting_result:1.0
    ports:
      - "80"
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

network:
    frontend:
    backend:

volumes:
    db-data: